using System.ComponentModel.DataAnnotations;

namespace BlockSense.Contracts.DTOs.TwoFactorAuth.Setup
{
    /// <summary>
    /// Represents a request to set up two-factor authentication (2FA) for a user account.
    /// </summary>
    public sealed record TwoFactorSetupRequest
    {
        /// <summary>
        /// The 20-byte (160-bit) Base32-encoded secret key used to configure 2FA in the authenticator app.
        /// </summary>
        [Required(ErrorMessage = "Secret key is required.")]
        [StringLength(32, MinimumLength = 32, ErrorMessage = "The secret key must be exactly 32 characters long.")]
        [RegularExpression(@"^[A-Z2-7]{32}$", ErrorMessage = "The secret key must be Base32 encoded (A-Z, 2-7).")]
        public string SecretKey { get; init; } = string.Empty;

        /// <summary>
        /// The 6-digit verification code generated by the authenticator app to confirm 2FA setup.
        /// </summary>
        [Required(ErrorMessage = "Two-factor authentication code is required.")]
        [StringLength(6, MinimumLength = 6, ErrorMessage = "The 2FA code must be exactly 6 characters long.")]
        [RegularExpression(@"^\d{6}$", ErrorMessage = "The 2FA code must consist of 6 digits.")]
        public string TwoFactorCode { get; init; } = string.Empty;
    }
}
