using BlockSense.Contracts.DTOs.Invitation;
using BlockSense.Contracts.DTOs.Session;

namespace BlockSense.Contracts.DTOs.User
{
    /// <summary>
    /// Represents the aggregated dashboard data for an authenticated user.
    /// </summary>
    public sealed record UserDashboardDto
    {
        /// <summary>
        /// The user's profile summary.
        /// </summary>
        public required UserSummaryDto Profile
        {
            get;
            init;
        }

        /// <summary>
        /// The list of currently active device sessions.
        /// </summary>
        public required IEnumerable<SessionDto> ActiveTokens
        {
            get;
            init;
        }

        /// <summary>
        /// The most recent activity log entries for the user.
        /// </summary>
        public required IEnumerable<ActivityLogDto> RecentActivity
        {
            get;
            init;
        }

        /// <summary>
        /// The invitations generated by or associated with the user.
        /// </summary>
        public required IEnumerable<InvitationDto> UserInvitations
        {
            get;
            init;
        }
    }
}