using BlockSense.Backend.Entities;

namespace BlockSense.Backend.Repositories.Interfaces
{
    /// <summary>
    /// Defines data access operations for managing invitation codes.
    /// </summary>
    public interface IInvitationRepository
    {
        /// <summary>
        /// Retrieves an invitation code by its unique identifier.
        /// </summary>
        /// <param name="invitationCodeId">The unique identifier of the invitation code.</param>
        /// <param name="cancellationToken">Optional token to cancel the operation.</param>
        /// <returns>The <see cref="InvitationCodeEntity"/> if found; otherwise, <c>null</c>.</returns>
        Task<InvitationCodeEntity?> GetByIdAsync(uint invitationCodeId, CancellationToken cancellationToken = default);
        /// <summary>
        /// Retrieves an invitation code by its string value.
        /// </summary>
        /// <param name="invitationCode">The invitation code string.</param>
        /// <param name="cancellationToken">Optional token to cancel the operation.</param>
        /// <returns>The <see cref="InvitationCodeEntity"/> if found; otherwise, <c>null</c>.</returns>
        Task<InvitationCodeEntity?> GetByCodeAsync(string invitationCode, CancellationToken cancellationToken = default);
        /// <summary>
        /// Retrieves an invitation code by its string value and locks the row for update.
        /// </summary>
        /// <param name="invitationCode">The invitation code string.</param>
        /// <param name="cancellationToken">Optional token to cancel the operation.</param>
        /// <returns>The <see cref="InvitationCodeEntity"/> if found; otherwise, <c>null</c>.</returns>
        Task<InvitationCodeEntity?> GetByCodeForUpdateAsync(string invitationCode, CancellationToken cancellationToken = default);

        /// <summary>
        /// Retrieves all invitation codes generated by a specific user.
        /// </summary>
        /// <param name="userId">The unique identifier of the user.</param>
        /// <param name="cancellationToken">Optional token to cancel the operation.</param>
        /// <returns>A collection of <see cref="InvitationCodeEntity"/> instances.</returns>
        Task<IReadOnlyList<InvitationCodeEntity>> GetByUserAsync(uint userId, CancellationToken cancellationToken = default);

        /// <summary>
        /// Retrieves a username of user who generated the invitation code.
        /// </summary>
        /// <param name="userId">The unique identifier of the user.</param>
        /// <param name="cancellationToken">Optional token to cancel the operation.</param>
        /// <returns>Username of user who generated the invitation code.</returns>
        Task<string?> GetGenerationUsernameByUsedUser(uint userId, CancellationToken cancellationToken = default);

        /// <summary>
        /// Checks whether an invitation code exists.
        /// </summary>
        /// <param name="invitationCode">The invitation code string.</param>
        /// <param name="cancellationToken">Optional token to cancel the operation.</param>
        /// <returns><c>true</c> if the code exists; otherwise, <c>false</c>.</returns>
        Task<bool> CodeExistsAsync(string invitationCode, CancellationToken cancellationToken = default);
        /// <summary>
        /// Determines whether an invitation code is active and usable.
        /// </summary>
        /// <param name="invitationCode">The invitation code string.</param>
        /// <param name="cancellationToken">Optional token to cancel the operation.</param>
        /// <returns><c>true</c> if the code is active; otherwise, <c>false</c>.</returns>
        Task<bool> IsCodeActiveAsync(string invitationCode, CancellationToken cancellationToken = default);

        /// <summary>
        /// Creates a new invitation code.
        /// </summary>
        /// <param name="invitation">The invitation code entity to persist.</param>
        /// <param name="cancellationToken">Optional token to cancel the operation.</param>
        /// <returns>The unique identifier of the newly created invitation code.</returns>
        Task<uint> CreateAsync(InvitationCodeEntity invitation, CancellationToken cancellationToken = default);

        /// <summary>
        /// Marks an invitation code as used.
        /// </summary>
        /// <param name="invitationCodeId">The unique identifier of the invitation code.</param>
        /// <param name="userId">The unique identifier of the user.</param>
        /// <param name="cancellationToken">Optional token to cancel the operation.</param>
        /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
        Task MarkAsUsedAsync(uint invitationCodeId, uint userId, CancellationToken cancellationToken = default);
        /// <summary>
        /// Revokes an invitation code, preventing future use.
        /// </summary>
        /// <param name="invitationCodeId">The unique identifier of the invitation code.</param>
        /// <param name="cancellationToken">Optional token to cancel the operation.</param>
        /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
        Task RevokeAsync(uint invitationCodeId, CancellationToken cancellationToken = default);
    }
}
